In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr


array([0, 1, 2, 3, 4])

In [4]:
# to save array in numpy we can use save() method as required
np.save('myarray1',arr)

In [5]:
p = np.load('myarray1')

IOError: [Errno 2] No such file or directory: 'myarray1'

In [7]:
# so above method did not workd out because we are not going to use in specified manner
p = np.load('myarray1.npy')

In [8]:
p

array([0, 1, 2, 3, 4])

In [14]:
# voilla so we are able to save array on memeory as well as load it when required. 
np.savez('ziparray.npz',x=arr)

In [15]:
m = np.load('ziparray.npz')

In [16]:
m

In [20]:
m['x']

array([0, 1, 2, 3, 4])

In [21]:
# ok now as we can see that we hava all the related things in need about various numpy functions
#savez() method saves arrays just like dictionar. 
# we can also save multiple arrays with savez() method as required in real life

# for example

arr2 = np.array([23,23,23,23])

In [22]:
arr2

array([23, 23, 23, 23])

In [23]:
np.savez('ziparray.npz',x=arr,y=arr2)

In [24]:
pp = np.load('ziparray.npz')

In [25]:
pp['y']

array([23, 23, 23, 23])

In [27]:
# bingggo :P :) we can also save various txt files using numpy

arr3 = np.array([[2,3,4],[4,5,6]])

In [28]:
arr3

array([[2, 3, 4],
       [4, 5, 6]])

In [29]:
np.savetxt('mytxtarray.txt',arr3)

In [30]:
txt = np.loadtxt('mytxtarray.txt')

In [31]:
txt


array([[ 2.,  3.,  4.],
       [ 4.,  5.,  6.]])

In [32]:
# IMportant note: make sure of one thing that whenever you save an array in any format don't forget to apply with 
# extension