In [1]:
#Python is fast and it is not just fast, it is increadibly fast.
# for example: 
print "Hello World"

Hello World


In [2]:
# so hello world just print "Hello World". :D
#other important thing in python is wide range of available libraries, 

# So what's wrong about Python? There should be some otherwise we can't say it is perfect or anything like that, 
# python is slow while our code do refrence-counting and typechecking in repeated-interval of time, For exampple:

def silly_func(N):
    d = 0.0
    for i in xrange(N):
        d+=(i%3-1)*i
    return d

In [3]:
%timeit silly_func(10000)

100 loops, best of 3: 2.04 ms per loop


Python is hogh level intepreted Dynamic Language, It does lot of type checking and refrence Counting where major amount of time is consumed. 

So here Numpy comes in the scene where you can use power of C in terms of SPEED and reliability of Python interms of fast development, So now we are talking about four strategies we can use to improve the speed of Python code using Numpy. 

1. Using Numpy's Ufuncs
2. Use Numpy's aggregations
3. Using Numpy's broadcasting
4. Using Numppy's sliccing,masking and fancyIndexing




In [4]:
# Ufuncs does element wise operations on arrays/lists

a = xrange(1000)

In [5]:
b = [i+5 for i in a]

In [6]:
%timeit b

10000000 loops, best of 3: 39.2 ns per loop


In [7]:
%timeit sum(b)

100000 loops, best of 3: 10.9 µs per loop


In [8]:
# ok now lets's fire-up Numpy. 
import numpy as np

In [9]:
b = np.array(a)

In [11]:
%timeit b+5

The slowest run took 25.35 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.04 µs per loop


In [12]:
%timeit np.sum(b)

The slowest run took 19.72 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 5.78 µs per loop


In [16]:
# so here in both the cases we can observe that our code is much faster, cleaner and useable

Now we can also do many other operations using Ufunc in Numpy as follows:

1. Airthmetic Operations: + , - , * ,// ,% , **
2. Bitwise operations: & , | , ^ , >> ,<< 
3. Comparison Operator: >, < , => , <=, != , ==
4. Trignometry Operations: np.sin,np.cos,np.tan , ....
5. Exponential Family : np.exp, np.log, np.log10, ....
6. Special Functions: scipy.special.* 

In [13]:
# Now Let's talk about using Numpy's aggregation, Which summerise the values of arrays. 
# for example, min, max, mean, mod etc

from random import random

b = [random() for i in xrange(10000)]



In [14]:
%timeit min(b)

1000 loops, best of 3: 396 µs per loop


In [15]:
np_array = np.array(b)

In [16]:
%timeit np_array.min()

The slowest run took 326.06 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 8.35 µs per loop


In [17]:
# there are also nanmin() nanmax() nansum() functions which are same but also able to do operations if Null,None, NaN 
#values exist in the python array

Now Let's Talk about Broadcasting, Broadcasting is set of rules by which ufuncs operate on arrays of different sizes 
or dimensions. 

Rules of BroadCasting:
1. If array shape is defferent, leftpad the smaller shape with 1s
2. if dimesnsion does not match broacast the dimension with size = 1
3. if neighter non matching dimension is one, raise an error

In [18]:
l = [2,3,4,5,6]


In [19]:
l[3:]

[5, 6]

In [29]:
# let's talk about 4th strategy, Slicing,masking and fancy-indexing in numpy

In [20]:
a = xrange(200)
b = np.array(a)
b[0]

0

In [21]:
b[5:25]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [22]:
b[:200]

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [23]:
b[200:]

array([], dtype=int64)

In [24]:
# now talk about MASKING which is quite more important to abolish the for loop condition:
l = np.array([2,4,5,6,7,8,9,9])

In [25]:
mask = np.array([True,True,True])

In [27]:
l[mask]

/home/metal-machine/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 8 but corresponding boolean dimension is 3
  if __name__ == '__main__':


array([2, 4, 5])

In [28]:
#so we have passed the condition in which looks for mask as condition: we can use masking in various cases as

# present python code

a = xrange(100000)
new_list = []
for i in a:
    if i%2==0:
        new_list.append(i)

In [29]:
%timeit new_list

The slowest run took 55.08 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 39 ns per loop


In [30]:
# now let's do similer thing using Numpy's masking approach:
a = np.array(xrange(100000))

In [31]:
a

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [32]:
mask = a%2==0

In [33]:
%timeit a[mask]

1000 loops, best of 3: 836 µs per loop


In [34]:
# let's talk about Fancy-indexing
fancy = [23,45,89] 
a[fancy] # i want 23rd,45th and 89th element on array a

array([23, 45, 89])

In [35]:
# all the above operations and fnctions are used to loose loops in Python and as Python Programmer one should think if one
# can loose loops as much as one can loose.  :)